const packages = {
    code: "ABT0000",
    plans: [
        {
            benefits: [
                "Invite to private discord",
                "Money distributions from basic royalty pool",
                "Voting rights to all polls",
                "Invite to digital premiere",
                "Chat permissions in most channels",
                "Name in credits",
                "Access to private channel",
                "Money distributions from producer pool",
                "Invite to in-person premiere",
                "Be in the movie!  Voice a character or include your music, we’ll work with you to see how we can involve you or someone you know",
            ],
            _id: "616eaeacaf156440cf7c7ec8",
            title: "Extra",
            total: 3,
            price: 1,
            createdAt: "2021-10-19T11:40:28.262Z",
            updatedAt: "2021-11-06T21:55:16.247Z",
            __v: 0,
            priceId: "price_1JswheIgsvrIdAscLqT4eQxK",
        },
        {
            benefits: [
                "Invite to private discord",
                "Money distributions from basic royalty pool",
                "Voting rights to all polls",
                "Invite to digital premiere",
                "Chat permissions in most channels",
                "Name in credits",
                "Access to private channel",
                "Money distributions from producer pool",
                "Invite to in-person premiere",
                "Be in the movie!  Voice a character or include your music, we’ll work with you to see how we can involve you or someone you know",
            ],
            _id: "616eaf7baf156440cf7c7ec9",
            title: "Assistant",
            total: 4,
            originalPrice: 10,
            price: 5,
            leftCount: 974,
            createdAt: "2021-10-19T11:43:55.688Z",
            updatedAt: "2022-01-22T17:57:02.700Z",
            __v: 0,
            priceId: "price_1JswiyIgsvrIdAscqcTzL3BW",
        },
        {
            benefits: [
                "Invite to private discord",
                "Money distributions from basic royalty pool",
                "Voting rights to all polls",
                "Invite to digital premiere",
                "Chat permissions in most channels",
                "Name in credits",
                "Access to private channel",
                "Money distributions from producer pool",
                "Invite to in-person premiere",
                "Be in the movie!  Voice a character or include your music, we’ll work with you to see how we can involve you or someone you know",
            ],
            _id: "616eafb6af156440cf7c7eca",
            title: "Gaffer",
            total: 5,
            originalPrice: 50,
            price: 30,
            leftCount: 795,
            createdAt: "2021-10-19T11:44:54.536Z",
            updatedAt: "2022-01-22T19:52:00.280Z",
            __v: 0,
            priceId: "price_1JswkJIgsvrIdAscwktXS2vL",
        },
        {
            benefits: [
                "Invite to private discord",
                "Money distributions from basic royalty pool",
                "Voting rights to all polls",
                "Invite to digital premiere",
                "Chat permissions in most channels",
                "Name in credits",
                "Access to private channel",
                "Money distributions from producer pool",
                "Invite to in-person premiere",
                "Be in the movie!  Voice a character or include your music, we’ll work with you to see how we can involve you or someone you know",
            ],
            _id: "616eb001af156440cf7c7ecb",
            title: "Stuntperson",
            total: 6,
            originalPrice: 200,
            price: 150,
            leftCount: 499,
            createdAt: "2021-10-19T11:46:09.574Z",
            updatedAt: "2022-01-22T20:37:04.459Z",
            __v: 0,
            priceId: "price_1JswlFIgsvrIdAsclswP5FEX",
        },
        {
            benefits: [
                "Invite to private discord",
                "Money distributions from basic royalty pool",
                "Voting rights to all polls",
                "Invite to digital premiere",
                "Chat permissions in most channels",
                "Name in credits",
                "Access to private channel",
                "Money distributions from producer pool",
                "Invite to in-person premiere",
                "Be in the movie!  Voice a character or include your music, we’ll work with you to see how we can involve you or someone you know",
            ],
            _id: "616eb039af156440cf7c7ecc",
            title: "Producer",
            total: 8,
            originalPrice: 1000,
            price: 800,
            leftCount: 100,
            createdAt: "2021-10-19T11:47:05.425Z",
            updatedAt: "2021-11-06T21:58:05.024Z",
            __v: 0,
            priceId: "price_1JswmUIgsvrIdAscpVHneuxE",
        },
        {
            benefits: [
                "Invite to private discord",
                "Money distributions from basic royalty pool",
                "Voting rights to all polls",
                "Invite to digital premiere",
                "Chat permissions in most channels",
                "Name in credits",
                "Access to private channel",
                "Money distributions from producer pool",
                "Invite to in-person premiere",
                "Be in the movie!  Voice a character or include your music, we’ll work with you to see how we can involve you or someone you know",
            ],
            _id: "616eb076af156440cf7c7ecd",
            title: "Executive",
            total: 9,
            originalPrice: 10000,
            price: 9000,
            leftCount: 8,
            createdAt: "2021-10-19T11:48:06.499Z",
            updatedAt: "2021-11-06T21:58:41.613Z",
            __v: 0,
            priceId: "price_1JswnDIgsvrIdAsc2J7pvnoR",
        },
    ],
};

export default packages;
